services:
  api:
    container_name: "IOTdevices_API"
    build:
      context: .
      dockerfile: DockerFile
    depends_on:
      - postgresql
    ports:
      - 8080:8082
    env_file:
      - ".env"
    networks:
      - backend

  postgresql:
    image: postgres:15-alpine
    container_name: "IOTdevices_DB"
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    expose:
      - 5432
    ports:
      - 5432:5432
    env_file:
      - ".env"
    networks:
      - backend
networks:
  backend:
    driver: bridge